name: check

on:
  push:
  pull_request:

jobs:
  flake:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - run: nix flake check --print-build-logs
      - run: nix develop -c shellcheck scripts/* tests/*.sh
